project:
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js

website:  
  title: "China's rise in the chemical space and the decline of US influence"
  navbar:
    search: true
    left:
      - text: "China’s rise in the CS"
        file: China-Chemical-Dominance.qmd
      - text: "Supplementary Materials"
        file: supp.qmd  
  page-footer: 
    left: "https://chemrxiv.org/engage/chemrxiv/article-details/67920ada6dde43c908f688f6"
    right: 
      - icon: file-earnark-pdf-fill
        href: https://github.com/coatless-tutorials/r-shinylive-data-include

lang: en

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
    theme: litera
    other-links:
      - text: NASA Open Data
        href: https://data.nasa.gov/
    code-links:
      - text: Data Import Code
        icon: file-code
        href: data-import.py

# Attach shinylive to every page
filters:
  - shinylive