project:
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js

website:  
  title: "China's rise in the chemical space and the decline of US influence"
  navbar:
    search: true
    left:
      - text: "China’s rise in the CS"
        file: China-Chemical-Dominance.qmd
      - text: "Supplementary Materials"
        file: sup.qmd  
  page-footer: 
    left: "https://chemrxiv.org/engage/chemrxiv/article-details/67920ada6dde43c908f688f6"
    right: 
      - icon: file-earnark-pdf-fill
        href: https://github.com/coatless-tutorials/r-shinylive-data-include

lang: en

format:
  html:
    grid: 
      body-width: 1350px
      sidebar-width: 200px
      margin-width: 160px
    toc: false
    theme: litera
    other-links:
      - text: "PDF"
        icon: file-pdf
        href: "https://chemrxiv.org/engage/api-gateway/chemrxiv/assets/orp/resource/item/67920ada6dde43c908f688f6/original/china-s-rise-in-the-chemical-space-and-the-decline-of-us-influence.pdf"
    code-links:
      - text: Data Code
        icon: file-code
        href: "https://raw.githubusercontent.com/santi-rios/China-Chemical-Dominance/refs/heads/main/data/collabs_df_ds.csv"


# Attach shinylive to every page
filters:
  - shinylive